language: ruby
services:
  - docker
before_script:
  - docker-compose up -d
  - sleep 5
script:
  - bundle exec rspec --pattern '**/*.spec.rb' --format d --fail-fast 3
after_success:
  - ./config/cap_deploy.sh master
after_script:
  - docker-compose down
env:
  global:
    secure: ENRxGUIGo1+G3DcJ6iLiJrOn05GIMuSGfHer2t9wRa55LQnkQUIj//BlEjBEVhSPYqdtePXK+cTonpoYy66bmtje/eB8FO6qyJsKCa0X6GS1Lcev+4el00jUDo8NyLSswVmUgVmduPfsFNFLxUeH9HSVOodhBdgEE0FjMNDl1I03hFjPNQ+5DDf4WLpcBa4qAApZh1hvtfhgXKBdub/WrElKTAvJswAVgtRjKHtJO3iT9vIJ/rX2Mr6na0nijLcHjCKvD4KJu81zRePETzfrmQ/V878Db74AH9GPUOHDEamVCHYDMm+NywW/UGtOCriI2bySOz4rHZyRzTuKN6Tv906lsf4hr3R/MjIdmA8e61xeW0a9JN+3i9b4Fsb+RKZpg/fJuV1ofVM7VD1SSaqR0hQg1HMTHb65+X2bmP3vRcCgorEMwfOFZkhELYko4q22CL+6OaITYfGJuo2GxcOjxOmNwF3buGpRq929CbeGDqKRRBpoE3Kz7YIqw8po4b+01lXAzP8bAVNtJIxcbgKFjQ83TaPpTG+yRpY38V5okTBCUB4AiAUW6EnLHWz7nMpxYZyVug0ia/OabDp4dPbqgv1xaRAOZHOzbwoXCWXpO8aAzRjpdGZ3FakfGtqkBbpoF8QOBACgIg6BdwuNdDAJGRG+rtsWiLtKLlvopy0T0n8=
