version: "3"
services:
  mongo:
    image: "mongo:latest"
    volumes:
      - "./init_db:/docker-entrypoint-initdb.d"
      - "./tmp/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo-admin"
      MONGO_INITDB_ROOT_PASSWORD: "pa$$word"
      MONGO_INITDB_DATABASE: "gamescripter"